### PR TITLE
Remove log level as label

### LINKED ISSUE #9: Best practice - log level as default label
Hi, thank you for the library.

One thing I've found is that this library adds a default label called 'level_name', this is discouraged by best practices: https://grafana.com/docs/loki/latest/best-practices/

Perhaps this could be removed?

### PR DESCRIPTION
**Pull request by barryvdh**
See https://grafana.com/docs/loki/latest/best-practices/
Fixes #9

### CODE REVIEW

**Comment by rrajkomar** [comment]
Hello, sorry took me a while to get back to that issue and search for the reason I added that specific label.

First of all, it seems the documentation was misunderstood in the first place : 
what is recommended in the best practices is to not use elements that have a great cardinality as labels, 
not add labels at all.

That being said, the reason I added it is that, by default, Loki only registers the levels as integer fields and I didn't find at the time a way to filter out the logs by level
After checking back I found out that by clicking on the level_names above the list of logs does the trick although it wasn't obvious.

Thanks for making the change.

**Comment by barryvdh** [comment]
But this does remove the level_name from the logs, so I don't think you can filter on that anymore? 
It says in the link you should just filter the rows based on content, not on label.

> For example, don’t add a level dynamic label, just |= "level=debug" instead.

**Comment by barryvdh** [comment]
Otherwise this might be something that could be added as config? (Or might be considered a breaking change now?)

**Comment by barryvdh** [comment]
Now that I think of it, it probably is pretty breaking for people relying on that label.

**Pull request merged**
