### PR TITLE
Remove labels from example

### PR DESCRIPTION
**Pull request by barryvdh**
Labels must be an array, not a string.

### CODE REVIEW

**Comment by rrajkomar** [comment]
Not familiar with Laravel apps myself so maybe @achetronic or @publiux could check it first.

**Review by publiux — COMMENTED** [review]
Looks good. phpdotenv does not support arrays. Thus, labels should be specified in a php array directly inside the config/logging.php file.

**Comment by achetronic** [comment]
> Labels must be an array, not a string.

If you tested it and it works, it is ok for me

**Comment by barryvdh** [comment]
Yeah it crashed otherwise.

**Pull request merged**
